export const configurePageElements = {
specsAndFeatureModalSections: [
  'Specifications',
  'Features',
],

specsAndFeatureModalSubSections: [
  'Measurement',
  'Steering',
  'Transmission',
  'Suspension',
  'Symmetrical All-Wheel Drive',
  'Performance',
  'Brakes',
  'Engine',
  'Wheels and Tyres',
  'Interior Trims',
  'Seating Extras',
  'Entertainment',
  'Collision Protection',
  'Collision Avoidance',
  'Security',
  'Instrumentation and Controls',
  'Exterior',
  'Air-conditioning',
  'Convenience',
  'Intelligent Driving Dynamics',
  'Storage',
  'Lighting Exterior',
  'Multi-Function Displays',
  'Chassis and Mechanism',
  'Child Safety',
  'Lighting - Interior',
],

variantTabButton: 'button[data-test="common:navBarButton:variant"]',
colourTabButton: 'button[data-test="common:navBarButton:subaru_colour"]',
colourAccordion: 'h3[data-test="accordion:toggle:sectionTitle:Colour"]',
interiorTabButton: 'button[data-test="common:navBarButton:subaru_interior"]',
interiorAccordion: 'h3[data-test="accordion:toggle:sectionTitle:Interior"]',
optionsTabButton: 'button[data-test="common:navBarButton:subaruaccessorypack"]',
optionsAccordion: 'h3[data-test="accordion:toggle:sectionTitle:Options"]',


};
