export const configurePageElements = {
specsAndFeatureModalSections: [
  'Specifications',
  'Features',
],

specsAndFeatureModalSubSections: [
  'Measurement',
  'Steering',
  'Transmission',
  'Suspension',
  'Symmetrical All-Wheel Drive',
  'Performance',
  'Brakes',
  'Engine',
  'Wheels and Tyres',
  'Interior Trims',
  'Seating Extras',
  'Entertainment',
  'Collision Protection',
  'Collision Avoidance',
  'Security',
  'Instrumentation and Controls',
  'Exterior',
  'Air-conditioning',
  'Convenience',
  'Intelligent Driving Dynamics',
  'Storage',
  'Lighting Exterior',
  'Multi-Function Displays',
  'Chassis and Mechanism',
  'Child Safety',
  'Lighting - Interior',
],

variantTabButton: 'button[data-test="common:navBarButton:variant"]',
colourTabButton: 'button[data-test="common:navBarButton:subaru_colour"]',
colourAccordion: 'h3[data-test="accordion:toggle:sectionTitle:Colour"]',
interiorTabButton: 'button[data-test="common:navBarButton:subaru_interior"]',
interiorAccordion: 'h3[data-test="accordion:toggle:sectionTitle:Interior"]',
optionsTabButton: 'button[data-test="common:navBarButton:subaruaccessorypack"]',
optionsAccordion: 'h3[data-test="accordion:toggle:sectionTitle:Options"]',

accessoriesTabButton: 'button[data-test="common:navBarButton:subaru_accessories"]',
accessoriesAccordion: 'h3[data-test="accordion:toggle:sectionTitle:Accessories"]',
protectionAccordion: 'div[data-test="accordion:category:Protection"]',
performancePartsAccordion: 'div[data-test="accordion:category:STI Performance Parts"]',
stylingAccordion: 'div[data-test="accordion:category:Styling"]',
cargoAccordion: 'div[data-test="accordion:category:Cargo"]',

protectionSummaryAmount:'h3[data-test="summary:selected:sectionTitle:Protection"]',
performancePartsSummaryAmount:'h3[data-test="summary:selected:sectionTitle:STI Performance Parts""]',
stylingSummaryAmount:'h3[data-test="summary:selected:sectionTitle:Styling"]',
cargoSummaryAmount:'h3[data-test="summary:selected:sectionTitle:Cargo"]',
servicePlanSummaryAmount:'div[data-test="summary_expanded:section:serviceplans"]',

servicePlansTabButton: 'button[data-test="common:navBarButton:serviceplans"]',
servicePlansAccordion: 'h3[data-test="accordion:toggle:sectionTitle:Service Plans"]',
servicePlanName: 'p[data-test="customise:featureServicePlanName"]',
servicePlanCheckbox: 'span[data-test="customise:featureServicePlanToggle"]',
priceGuideLink: 'a[data-test="customise:featureServicePlanPriceGuide"]',
serviceName: 'div[data-test="customise:featureServicePlanInterval"]',
servicePrice: 'span[data-test="customise:featureServicePlanInterval:price"]',
servicePlanTotalPrice: 'span[data-test="customise:featureServicePlanIntervalTotal"]',
servicePlanPrice: 'span[data-test="customise:featureServicePlanPrice"]',

financeButton: 'button[data-test="button:finance_product_tabs:finance"]',
continueButtonCalculateModal: 'button[data-test="calculator:continueButton"]',



};
